
## static_countries

UPDATE static_countries SET cn_short_es='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_es='Emiratos Árabes Unidos' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_es='Afganistán' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_es='Antigua y Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_es='Anguila' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_es='Albania' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_es='Armenia' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_es='Antillas Neerlandesas' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_es='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_es='Antártida' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_es='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_es='Samoa Americana' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_es='Austria' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_es='Australia' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_es='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_es='Azerbaiyán' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_es='Bosnia-Herzegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_es='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_es='Bangladesh' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_es='Bélgica' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_es='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_es='Bulgaria' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_es='Bahráin' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_es='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_es='Benín' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_es='Bermudas' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_es='Brunéi' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_es='Bolivia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_es='Brasil' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_es='Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_es='Bután' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_es='Isla Bouvet' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_es='Botsuana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_es='Bielorrusia' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_es='Belice' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_es='Canadá' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_es='Islas Cocos (Keeling)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_es='República Democrática del Congo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_es='República Centroafricana' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_es='Congo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_es='Suiza' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_es='Costa de Marfil' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_es='Islas Cook' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_es='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_es='Camerún' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_es='China' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_es='Colombia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_es='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_es='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_es='Cabo Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_es='Isla Navidad' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_es='Chipre' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_es='República Checa' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_es='Alemania' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_es='Yibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_es='Dinamarca' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_es='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_es='República Dominicana' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_es='Argelia' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_es='Ecuador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_es='Estonia' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_es='Egipto' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_es='Sáhara Occidental' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_es='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_es='España' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_es='Etiopía' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_es='Finlandia' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_es='Fiyi' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_es='Islas Falkland (Malvinas)' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_es='Micronesia' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_es='Islas Feroe' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_es='Francia' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_es='Gabón' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_es='Reino Unido' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_es='Granada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_es='Georgia' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_es='Guayana Francesa' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_es='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_es='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_es='Groenlandia' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_es='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_es='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_es='Guadalupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_es='Guinea Ecuatorial' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_es='Grecia' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_es='Islas Georgia del Sur y Sandwich del Sur' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_es='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_es='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_es='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_es='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_es='Hong-Kong, Región administrativa especial de Chin' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_es='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_es='Croacia' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_es='Haití' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_es='Hungría' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_es='Indonesia' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_es='Irlanda' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_es='Israel' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_es='India' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_es='Territorios Británico del Océano Índico' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_es='Iraq' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_es='Irán' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_es='Islandia' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_es='Italia' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_es='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_es='Jordania' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_es='Japón' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_es='Kenia' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_es='Kirguizistán' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_es='Camboya' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_es='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_es='Comoras' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_es='San Cristóbal y Nieves' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_es='Corea del Norte' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_es='Corea del Sur' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_es='Kuwait' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_es='Islas Caimán' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_es='Kazajstán' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_es='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_es='Líbano' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_es='Saint Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_es='Liechtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_es='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_es='Liberia' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_es='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_es='Lituania' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_es='Luxemburgo' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_es='Letonia' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_es='Libia' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_es='Marruecos' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_es='Mónaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_es='Moldova' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_es='Madagascar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_es='Islas Marshall' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_es='Macedonia' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_es='Malí' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_es='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_es='Mongolia' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_es='Macao, Región administrativa especial de China' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_es='Islas Marianas del Norte' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_es='Martinica' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_es='Mauritania' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_es='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_es='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_es='Mauricio' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_es='Maldivas' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_es='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_es='México' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_es='Malasia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_es='Mozambique' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_es='Namibia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_es='Nueva Caledonia' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_es='Níger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_es='Isla Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_es='Nigeria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_es='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_es='Países Bajos' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_es='Noruega' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_es='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_es='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_es='Isla Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_es='Nueva Zelanda' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_es='Omán' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_es='Panamá' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_es='Perú' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_es='Polinesia Francesa' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_es='Papúa Nueva Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_es='Filipinas' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_es='Pakistán' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_es='Polonia' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_es='San Pedro y Miquelón' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_es='Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_es='Puerto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_es='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_es='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_es='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_es='Qatar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_es='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_es='Rumanía' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_es='Rusia' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_es='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_es='Arabia Saudí' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_es='Islas Salomón' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_es='Seychelles' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_es='Sudán' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_es='Suecia' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_es='Singapur' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_es='Santa Elena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_es='Eslovenia' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_es='Svalbard y Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_es='Eslovaquia' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_es='Sierra Leona' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_es='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_es='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_es='Somalia' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_es='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_es='Santo Tomé y Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_es='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_es='Siria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_es='Suazilandia' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_es='Islas Turcas y Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_es='Chad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_es='Territorios Australes Franceses' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_es='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_es='Tailandia' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_es='Tayikistán' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_es='Islas Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_es='Turkmenistán' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_es='Túnez' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_es='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_es='Timor Oriental' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_es='Turquía' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_es='Trinidad y Tabago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_es='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_es='Taiwán' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_es='Tanzania' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_es='Ucrania' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_es='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_es='Islas menores alejadas de los Estados Unidos' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_es='Estados Unidos' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_es='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_es='Uzbekistán' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_es='Ciudad del Vaticano' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_es='San Vicente y las Granadinas' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_es='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_es='Islas Vírgenes Británicas' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_es='Islas Vírgenes de los Estados Unidos' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_es='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_es='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_es='Wallis y Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_es='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_es='Yemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_es='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_es='Sudáfrica' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_es='Zambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_es='Zimbabue' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_es='Territorios Palestinos' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_es='Serbia y Montenegro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_es='Las islas de Åland' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_es='Islas Heard y McDonald' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_es='Montenegro' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_es='Serbia' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_es='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_es='Guernesey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_es='Isla de Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_es='San Martín' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_es='San Bartolomé' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_es='Bonaire, San Eustaquio y Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_es='Curazao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_es='Sint Maarten' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_es='Sudán del Sur' WHERE cn_iso_2='SS';

## static_currencies

UPDATE static_currencies SET cu_name_es='dirham de los Emiratos Árabes Unidos',cu_sub_name_es='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_es='lek albanés',cu_sub_name_es='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_es='dram armenio',cu_sub_name_es='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_es='florín de las Antillas Neerlandesas',cu_sub_name_es='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_es='kwanza angoleño',cu_sub_name_es='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_es='peso argentino',cu_sub_name_es='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_es='dólar australiano',cu_sub_name_es='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_es='florín de Aruba',cu_sub_name_es='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_es='manat azerbaiyano',cu_sub_name_es='' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_es='marco bosnio convertible',cu_sub_name_es='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_es='dólar de Barbados',cu_sub_name_es='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_es='taka de Bangladesh',cu_sub_name_es='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_es='nuevo lev búlgaro',cu_sub_name_es='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_es='dinar bahreiní',cu_sub_name_es='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_es='franco de Burundi',cu_sub_name_es='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_es='dólar de Bermudas',cu_sub_name_es='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_es='dólar de Brunéi',cu_sub_name_es='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_es='boliviano',cu_sub_name_es='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_es='real brasileño',cu_sub_name_es='' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_es='dólar de las Bahamas',cu_sub_name_es='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_es='ngultrum butanés',cu_sub_name_es='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_es='pula botsuano',cu_sub_name_es='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_es='rublo bielorruso',cu_sub_name_es='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_es='dólar de Belice',cu_sub_name_es='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_es='dólar canadiense',cu_sub_name_es='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_es='franco congoleño',cu_sub_name_es='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_es='franco suizo',cu_sub_name_es='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_es='peso chileno',cu_sub_name_es='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_es='yuan renminbi chino',cu_sub_name_es='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_es='peso colombiano',cu_sub_name_es='' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_es='colón costarricense',cu_sub_name_es='' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_es='peso cubano',cu_sub_name_es='' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_es='escudo de Cabo Verde',cu_sub_name_es='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_es='libra chipriota',cu_sub_name_es='' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_es='corona checa',cu_sub_name_es='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_es='franco de Yibuti',cu_sub_name_es='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_es='corona danesa',cu_sub_name_es='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_es='peso dominicano',cu_sub_name_es='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_es='dinar argelino',cu_sub_name_es='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_es='corona estonia',cu_sub_name_es='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_es='libra egipcia',cu_sub_name_es='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_es='nakfa eritreo',cu_sub_name_es='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_es='birr etíope',cu_sub_name_es='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_es='euro',cu_sub_name_es='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_es='dólar de las Islas Fiyi',cu_sub_name_es='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_es='libra de las Islas Malvinas',cu_sub_name_es='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_es='libra esterlina británica',cu_sub_name_es='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_es='lari georgiano',cu_sub_name_es='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_es='cedi ghanés',cu_sub_name_es='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_es='libra de Gibraltar',cu_sub_name_es='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_es='dalasi gambiano',cu_sub_name_es='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_es='franco guineo',cu_sub_name_es='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_es='quetzal guatemalteco',cu_sub_name_es='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_es='peso de Guinea-Bissáu',cu_sub_name_es='' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_es='dólar guyanés',cu_sub_name_es='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_es='dólar de Hong Kong',cu_sub_name_es='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_es='lempira hondureño',cu_sub_name_es='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_es='kuna croata',cu_sub_name_es='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_es='gourde haitiano',cu_sub_name_es='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_es='forinto húngaro',cu_sub_name_es='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_es='rupia indonesia',cu_sub_name_es='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_es='nuevo sheqel israelí',cu_sub_name_es='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_es='rupia india',cu_sub_name_es='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_es='dinar iraquí',cu_sub_name_es='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_es='rial iraní',cu_sub_name_es='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_es='corona islandesa',cu_sub_name_es='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_es='dólar de Jamaica',cu_sub_name_es='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_es='dinar jordano',cu_sub_name_es='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_es='yen japonés',cu_sub_name_es='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_es='chelín keniata',cu_sub_name_es='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_es='som kirguís',cu_sub_name_es='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_es='riel camboyano',cu_sub_name_es='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_es='franco comorense',cu_sub_name_es='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_es='won norcoreano',cu_sub_name_es='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_es='won surcoreano',cu_sub_name_es='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_es='dinar kuwaití',cu_sub_name_es='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_es='dólar de las Islas Caimán',cu_sub_name_es='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_es='tenge kazako',cu_sub_name_es='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_es='kip laosiano',cu_sub_name_es='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_es='libra libanesa',cu_sub_name_es='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_es='rupia de Sri Lanka',cu_sub_name_es='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_es='dólar liberiano',cu_sub_name_es='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_es='loti lesothense',cu_sub_name_es='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_es='litas lituano',cu_sub_name_es='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_es='lats letón',cu_sub_name_es='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_es='dinar libio',cu_sub_name_es='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_es='dirham marroquí',cu_sub_name_es='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_es='leu moldavo',cu_sub_name_es='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_es='dinar macedonio',cu_sub_name_es='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_es='kyat de Myanmar',cu_sub_name_es='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_es='tugrik mongol',cu_sub_name_es='' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_es='pataca de Macao',cu_sub_name_es='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_es='ouguiya mauritano',cu_sub_name_es='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_es='lira maltesa',cu_sub_name_es='' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_es='rupia mauriciana',cu_sub_name_es='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_es='rufiyaa de Maldivas',cu_sub_name_es='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_es='kwacha de Malawi',cu_sub_name_es='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_es='peso mexicano',cu_sub_name_es='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_es='ringgit malasio',cu_sub_name_es='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_es='metical mozambiqueño',cu_sub_name_es='' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_es='dólar de Namibia',cu_sub_name_es='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_es='naira nigeriano',cu_sub_name_es='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_es='córdoba oro nicaragüense',cu_sub_name_es='' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_es='corona noruega',cu_sub_name_es='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_es='rupia nepalesa',cu_sub_name_es='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_es='dólar neozelandés',cu_sub_name_es='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_es='rial omaní',cu_sub_name_es='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_es='balboa panameño',cu_sub_name_es='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_es='nuevo sol peruano',cu_sub_name_es='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_es='kina de Papúa Nueva Guinea',cu_sub_name_es='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_es='peso filipino',cu_sub_name_es='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_es='rupia pakistaní',cu_sub_name_es='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_es='zloty polaco',cu_sub_name_es='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_es='guaraní paraguayo',cu_sub_name_es='' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_es='riyal de Qatar',cu_sub_name_es='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_es='leu rumano',cu_sub_name_es='' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_es='rublo ruso',cu_sub_name_es='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_es='franco ruandés',cu_sub_name_es='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_es='riyal saudí',cu_sub_name_es='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_es='dólar de las Islas Salomón',cu_sub_name_es='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_es='rupia de Seychelles',cu_sub_name_es='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_es='libra sudanesa',cu_sub_name_es='' WHERE cu_iso_3='SDG';
UPDATE static_currencies SET cu_name_es='corona sueca',cu_sub_name_es='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_es='dólar singapurense',cu_sub_name_es='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_es='libra de Santa Elena',cu_sub_name_es='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_es='tólar esloveno',cu_sub_name_es='' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_es='corona eslovaca',cu_sub_name_es='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_es='leone de Sierra Leona',cu_sub_name_es='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_es='chelín somalí',cu_sub_name_es='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_es='dobra de Santo Tomé y Príncipe',cu_sub_name_es='' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_es='colón salvadoreño',cu_sub_name_es='' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_es='libra siria',cu_sub_name_es='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_es='lilangeni suazi',cu_sub_name_es='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_es='baht tailandés',cu_sub_name_es='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_es='somoni tayiko',cu_sub_name_es='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_es='manat turcomano',cu_sub_name_es='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_es='dinar tunecino',cu_sub_name_es='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_es='paʻanga tongano',cu_sub_name_es='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_es='dólar de Trinidad y Tobago',cu_sub_name_es='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_es='nuevo dólar taiwanés',cu_sub_name_es='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_es='chelín tanzano',cu_sub_name_es='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_es='grivna ucraniana',cu_sub_name_es='' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_es='chelín ugandés',cu_sub_name_es='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_es='dólar estadounidense',cu_sub_name_es='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_es='peso uruguayo',cu_sub_name_es='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_es='sum uzbeko',cu_sub_name_es='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_es='bolívar venezolano',cu_sub_name_es='' WHERE cu_iso_3='VEF';
UPDATE static_currencies SET cu_name_es='dong vietnamita',cu_sub_name_es='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_es='vatu vanuatuense',cu_sub_name_es='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_es='tala samoano',cu_sub_name_es='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_es='franco CFA BEAC',cu_sub_name_es='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_es='dólar del Caribe Oriental',cu_sub_name_es='' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_es='franco CFA BCEAO',cu_sub_name_es='' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_es='franco CFP',cu_sub_name_es='' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_es='rial yemení',cu_sub_name_es='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_es='rand sudafricano',cu_sub_name_es='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_es='kwacha zambiano',cu_sub_name_es='' WHERE cu_iso_3='ZMW';
UPDATE static_currencies SET cu_name_es='dólar de Zimbabue',cu_sub_name_es='' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_es='afgani',cu_sub_name_es='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_es='dinar serbio',cu_sub_name_es='' WHERE cu_iso_3='RSD';
UPDATE static_currencies SET cu_name_es='ariary malgache',cu_sub_name_es='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_es='dólar surinamés',cu_sub_name_es='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_es='lira turca',cu_sub_name_es='' WHERE cu_iso_3='TRY';
UPDATE static_currencies SET cu_name_es='libra sursudanesa',cu_sub_name_es='' WHERE cu_iso_3='SSP';
UPDATE static_currencies SET cu_name_es='cedi ghanés',cu_sub_name_es='' WHERE cu_iso_3='GHS';
UPDATE static_currencies SET cu_name_es='metical mozambiqueño',cu_sub_name_es='' WHERE cu_iso_3='MZN';
UPDATE static_currencies SET cu_name_es='leu rumano',cu_sub_name_es='' WHERE cu_iso_3='RON';
UPDATE static_currencies SET cu_name_es='manat turcomano',cu_sub_name_es='' WHERE cu_iso_3='TMT';

## static_languages

UPDATE static_languages SET lg_name_es='abkhaziano' WHERE lg_iso_2='AB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='afar' WHERE lg_iso_2='AA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='afrikaans' WHERE lg_iso_2='AF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='albanés' WHERE lg_iso_2='SQ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='amárico' WHERE lg_iso_2='AM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='árabe' WHERE lg_iso_2='AR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='armenio' WHERE lg_iso_2='HY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='asamés' WHERE lg_iso_2='AS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='aymara' WHERE lg_iso_2='AY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='azerí' WHERE lg_iso_2='AZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='bashkir' WHERE lg_iso_2='BA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='vasco' WHERE lg_iso_2='EU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='bengalí' WHERE lg_iso_2='BN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='bhutaní' WHERE lg_iso_2='DZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='bihari' WHERE lg_iso_2='BH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='bislama' WHERE lg_iso_2='BI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='bretón' WHERE lg_iso_2='BR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='búlgaro' WHERE lg_iso_2='BG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='birmano' WHERE lg_iso_2='MY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='bielorruso' WHERE lg_iso_2='BE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='jemer' WHERE lg_iso_2='KM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='catalán' WHERE lg_iso_2='CA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='zhuang' WHERE lg_iso_2='ZA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='chino' WHERE lg_iso_2='ZH' AND lg_country_iso_2='HK';
UPDATE static_languages SET lg_name_es='corso' WHERE lg_iso_2='CO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='croata' WHERE lg_iso_2='HR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='checo' WHERE lg_iso_2='CS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='danés' WHERE lg_iso_2='DA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='holandés' WHERE lg_iso_2='NL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='inglés' WHERE lg_iso_2='EN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='esperanto' WHERE lg_iso_2='EO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='estonio' WHERE lg_iso_2='ET' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='feroés' WHERE lg_iso_2='FO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='farsi' WHERE lg_iso_2='FA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='fidji' WHERE lg_iso_2='FJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='finlandés' WHERE lg_iso_2='FI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='francés' WHERE lg_iso_2='FR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='frisón' WHERE lg_iso_2='FY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='gallego' WHERE lg_iso_2='GL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='gaélico escocés' WHERE lg_iso_2='GD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='gaélico manés' WHERE lg_iso_2='GV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='georgiano' WHERE lg_iso_2='KA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='alemán' WHERE lg_iso_2='DE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='griego' WHERE lg_iso_2='EL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='groenlandés' WHERE lg_iso_2='KL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='guaraní' WHERE lg_iso_2='GN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='gujarati' WHERE lg_iso_2='GU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='hausa' WHERE lg_iso_2='HA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='hebreo' WHERE lg_iso_2='HE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='hindi' WHERE lg_iso_2='HI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='húngaro' WHERE lg_iso_2='HU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='islandés' WHERE lg_iso_2='IS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='indonesio' WHERE lg_iso_2='ID' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='interlingua' WHERE lg_iso_2='IA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='interlingue' WHERE lg_iso_2='IE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='inuktitut' WHERE lg_iso_2='IU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='inupiak' WHERE lg_iso_2='IK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='irlandés' WHERE lg_iso_2='GA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='italiano' WHERE lg_iso_2='IT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='japonés' WHERE lg_iso_2='JA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='canarés' WHERE lg_iso_2='KN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='cachemiro' WHERE lg_iso_2='KS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='kazajo' WHERE lg_iso_2='KK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='kinyarwanda' WHERE lg_iso_2='RW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='kirghiz' WHERE lg_iso_2='KY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='kiroundi' WHERE lg_iso_2='RN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='coreano' WHERE lg_iso_2='KO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='kurdo' WHERE lg_iso_2='KU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='laosiano' WHERE lg_iso_2='LO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='latín' WHERE lg_iso_2='LA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='letón' WHERE lg_iso_2='LV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='lingala' WHERE lg_iso_2='LN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='lituano' WHERE lg_iso_2='LT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='macedonio' WHERE lg_iso_2='MK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='malgache' WHERE lg_iso_2='MG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='malayo' WHERE lg_iso_2='MS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='malayalam' WHERE lg_iso_2='ML' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='maltés' WHERE lg_iso_2='MT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='maorí' WHERE lg_iso_2='MI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='marathi' WHERE lg_iso_2='MR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='moldavo' WHERE lg_iso_2='MO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='mongol' WHERE lg_iso_2='MN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='nauruano' WHERE lg_iso_2='NA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='nepalí' WHERE lg_iso_2='NE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='noruego' WHERE lg_iso_2='NO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='occitano (después del 1500)' WHERE lg_iso_2='OC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='oriya' WHERE lg_iso_2='OR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='oromo' WHERE lg_iso_2='OM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='pashto' WHERE lg_iso_2='PS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='polaco' WHERE lg_iso_2='PL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='portugués' WHERE lg_iso_2='PT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='punjabí' WHERE lg_iso_2='PA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='quechua' WHERE lg_iso_2='QU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='reto-romance' WHERE lg_iso_2='RM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='rumano' WHERE lg_iso_2='RO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='ruso' WHERE lg_iso_2='RU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='samoano' WHERE lg_iso_2='SM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='sango' WHERE lg_iso_2='SG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='sánscrito' WHERE lg_iso_2='SA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='serbio' WHERE lg_iso_2='SR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='sesotho' WHERE lg_iso_2='ST' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='setchwana' WHERE lg_iso_2='TN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='shona' WHERE lg_iso_2='SN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='sindhi' WHERE lg_iso_2='SD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='singalés' WHERE lg_iso_2='SI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='siswati' WHERE lg_iso_2='SS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='eslovaco' WHERE lg_iso_2='SK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='esloveno' WHERE lg_iso_2='SL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='somalí' WHERE lg_iso_2='SO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='español' WHERE lg_iso_2='ES' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='sundanés' WHERE lg_iso_2='SU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='swahili' WHERE lg_iso_2='SW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='sueco' WHERE lg_iso_2='SV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='tagalo' WHERE lg_iso_2='TL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='tayiko' WHERE lg_iso_2='TG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='tamil' WHERE lg_iso_2='TA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='tatar' WHERE lg_iso_2='TT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='telugu' WHERE lg_iso_2='TE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='tailandés' WHERE lg_iso_2='TH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='tibetano' WHERE lg_iso_2='BO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='tigrinya' WHERE lg_iso_2='TI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='tonga (Islas Tonga)' WHERE lg_iso_2='TO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='tsonga' WHERE lg_iso_2='TS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='turco' WHERE lg_iso_2='TR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='turkmeno' WHERE lg_iso_2='TK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='twi' WHERE lg_iso_2='TW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='uigur' WHERE lg_iso_2='UG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='ucraniano' WHERE lg_iso_2='UK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='urdu' WHERE lg_iso_2='UR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='uzbeko' WHERE lg_iso_2='UZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='vietnamita' WHERE lg_iso_2='VI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='volapuk' WHERE lg_iso_2='VO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='galés' WHERE lg_iso_2='CY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='uolof' WHERE lg_iso_2='WO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='xhosa' WHERE lg_iso_2='XH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='yidish' WHERE lg_iso_2='YI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='yoruba' WHERE lg_iso_2='YO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='zulú' WHERE lg_iso_2='ZU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='bosnio' WHERE lg_iso_2='BS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='avéstico' WHERE lg_iso_2='AE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='akan' WHERE lg_iso_2='AK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='aragonés' WHERE lg_iso_2='AN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='avar' WHERE lg_iso_2='AV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='bambara' WHERE lg_iso_2='BM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='checheno' WHERE lg_iso_2='CE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='chamorro' WHERE lg_iso_2='CH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='cree' WHERE lg_iso_2='CR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='eslavo eclesiástico' WHERE lg_iso_2='CU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='chuvash' WHERE lg_iso_2='CV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='divehi' WHERE lg_iso_2='DV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='ewe' WHERE lg_iso_2='EE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='fula' WHERE lg_iso_2='FF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='hiri motu' WHERE lg_iso_2='HO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='haitiano' WHERE lg_iso_2='HT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='herero' WHERE lg_iso_2='HZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='igbo' WHERE lg_iso_2='IG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='sichuan yi' WHERE lg_iso_2='II' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='ido' WHERE lg_iso_2='IO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='javanés' WHERE lg_iso_2='JV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='kongo' WHERE lg_iso_2='KG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='kikuyu' WHERE lg_iso_2='KI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='kuanyama' WHERE lg_iso_2='KJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='kanuri' WHERE lg_iso_2='KR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='komi' WHERE lg_iso_2='KV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='córnico' WHERE lg_iso_2='KW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='luxemburgués' WHERE lg_iso_2='LB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='ganda' WHERE lg_iso_2='LG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='limburgués' WHERE lg_iso_2='LI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='luba-katanga' WHERE lg_iso_2='LU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='marshalés' WHERE lg_iso_2='MH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='bokmal noruego' WHERE lg_iso_2='NB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='ndebele septentrional' WHERE lg_iso_2='ND' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='ndonga' WHERE lg_iso_2='NG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='nynorsk noruego' WHERE lg_iso_2='NN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='ndebele meridional' WHERE lg_iso_2='NR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='navajo' WHERE lg_iso_2='NV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='nyanja' WHERE lg_iso_2='NY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='ojibwa' WHERE lg_iso_2='OJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='osético' WHERE lg_iso_2='OS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='pali' WHERE lg_iso_2='PI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='sardo' WHERE lg_iso_2='SC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='sami septentrional' WHERE lg_iso_2='SE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='tahitiano' WHERE lg_iso_2='TY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='venda' WHERE lg_iso_2='VE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='valón' WHERE lg_iso_2='WA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_es='portugués' WHERE lg_iso_2='PT' AND lg_country_iso_2='BR';
UPDATE static_languages SET lg_name_es='chino' WHERE lg_iso_2='ZH' AND lg_country_iso_2='CN';
UPDATE static_languages SET lg_name_es='' WHERE lg_iso_2='FR' AND lg_country_iso_2='CA';
UPDATE static_languages SET lg_name_es='' WHERE lg_iso_2='TL' AND lg_country_iso_2='PH';
UPDATE static_languages SET lg_name_es='' WHERE lg_iso_2='SR' AND lg_country_iso_2='ME';

## static_territories

UPDATE static_territories SET tr_name_es='África' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_es='Oceanía' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_es='América' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_es='Asia' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_es='Europa' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_es='Asia Oriental' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_es='Sudeste Asiático' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_es='Asia Central' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_es='Asia Occidental' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_es='Europa Meridional' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_es='Europa Oriental' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_es='Europa del Norte' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_es='Europa Occidental' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_es='América del Sur' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_es='América Central' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_es='América del Norte' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_es='Caribe' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_es='África Occidental' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_es='África Oriental' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_es='Norte de África' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_es='África Central' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_es='África austral' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_es='Australia y Nueva Zelanda' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_es='Melanesia' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_es='Micronesia' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_es='Polinesia' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_es='Asia del Sur' WHERE tr_iso_nr='34';
UPDATE static_territories SET tr_name_es='' WHERE tr_iso_nr='419';